import Navbar from '../components/NavBar'
import Footer from '../components/Footer'
import './globals.css'
import Link from 'next/link';

export const metadata = {
  title: 'Next App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
